### ISSUE TITLE
404 Error Submissions

### ISSUE THREAD

**Issue by lexinal** [sidlowsh/wp-content#1]
Hi Sarah, 

I really liked how the 404 error page fit the theme of your page. Also, I liked how you also went further into customizing the 404 error page by having another 404 error page pop up with different size of text for if a person searched something that didn't exist. I wish I thought of that!

**Comment by sidlowsh** [comment]
Thanks Alexia! It was pretty easy, if you want to add it to your site! Just do the same thing you did for the 404.php file with the search.php file!
