### ISSUE TITLE
fix metabox save/display issues

### ISSUE THREAD

**Issue by greglinch** [sidlowsh/wp-content#18]
Adding here for reference based on what you mentioned in class. Please comment here when there's an update.

**Comment by sidlowsh** [comment]
Update: Metabox data saves and displays for Job Board single entries. Here's an example link: http://scsstudentlife.com/jobs/animal-care-technician-division-of-comparative-medicine.

Still working on Event post type, but if I want to get it to work seamlessly, am thinking about going down to one metabox field to match working Jobs post type.
