### ISSUE TITLE
Images 

### ISSUE THREAD

**Issue by Faherelfayez** [sidlowsh/wp-content#3]
I would add more images to make the site to make more interactive. Right now it seems more news telling.

**Comment by szs10** [comment]
I agree, images would definitely help and make your website more visually appealing. I probably shared it with everyone right now, however if you're looking for a good source of free, high quality photos, you should check out [Unsplash](https://unsplash.com).

**Comment by sidlowsh** [comment]
Thank you both! This is really helpful and definitely on my list!
