### ISSUE TITLE
Job Board

### ISSUE THREAD

**Issue by szs10** [sidlowsh/wp-content#8]
Posting job opportunities on the website is a great idea! It would probably be a hard coding process, but I was thinking about making it possible for the users to submit their resumes through your website. For example, [Indeed](https://www.indeed.com) offers this function, that definitely saves time and improves user experience.

**Comment by sidlowsh** [comment]
Great idea! I'm sure there's a plug-in that would allow this. I wonder if my site would be secure enough for students to submit personal information...

Definitely something to look into!
